define({
  canvas : gCanvas,
  ctx : gCtx,
  ballX : 0,
  ballRadius : 10,
  ballY : 0,
  ballDx : 4,
  ballDy : -4,
  paddleHeight : 10,
  paddleWidth : 75,
  paddleX : 0,
  rightPressed : false,
  leftPressed : false,
  ballOver : false,
  brickRowCount : 3,
  brickColumnCount : 5,
  brickWidth : 75,
  brickHeight : 20,
  brickPadding : 10,
  brickOffsetTop : 30,
  brickOffsetLeft : 30,
  bricks : [],
  score : 0,
  lives : 3
});